# Generated by Django 3.2.3 on 2021-07-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0003_bill_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='method',
        ),
    ]
